steps:
- name: 'gcr.io/cloud-builders/docker'
  id: create-us-image
  args:
  - build
  - -t
  - ${_US_IMAGE}
  - .

- name: 'gcr.io/cloud-builders/docker'
  id: save-us-image
  args:
  - push
  - ${_US_IMAGE}


substitutions:
  _AR_REGION: northamerica-northeast1-docker.pkg.dev
  _AR_REPO: vic
  _US_NAME: grupo1-1
  _US_IMAGE: ${_AR_REGION}/${PROJECT_ID}/${_AR_REPO}/${_US_NAME}
